/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lista2.atividade2;

import javax.swing.JOptionPane;

/**
 *
 * @author felip
 */
public class tela extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
        jRbtnPedra.setSelected(true);//impossibilitar de não escolher nenhuma opção
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRbtnPedra = new javax.swing.JRadioButton();
        jRbtnPapel = new javax.swing.JRadioButton();
        jRbtnTesoura = new javax.swing.JRadioButton();
        jBtnJogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Pedra, Papel ou Tesoura?");

        buttonGroup1.add(jRbtnPedra);
        jRbtnPedra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRbtnPedra.setText("Pedra");

        buttonGroup1.add(jRbtnPapel);
        jRbtnPapel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRbtnPapel.setText("Papel");
        jRbtnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtnPapelActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRbtnTesoura);
        jRbtnTesoura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRbtnTesoura.setText("Tesoura");

        jBtnJogar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnJogar.setText("Jogar");
        jBtnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnJogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnJogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRbtnPedra)
                                .addGap(49, 49, 49)
                                .addComponent(jRbtnPapel)
                                .addGap(41, 41, 41)
                                .addComponent(jRbtnTesoura)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbtnPedra)
                    .addComponent(jRbtnPapel)
                    .addComponent(jRbtnTesoura))
                .addGap(18, 18, 18)
                .addComponent(jBtnJogar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRbtnPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtnPapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbtnPapelActionPerformed

    public static int randInt(int min,int max) {
        java.util.Random rand = new java.util.Random();
        int randomNum = rand.nextInt((max-min)+1)+min;
        return randomNum;
    }
    
    private void jBtnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnJogarActionPerformed
        if(jBtnJogar.getText()=="Jogar"){
          int Computador = randInt(0,2);
           if(Computador == 0){
              if(jRbtnPapel.isSelected()){
                  JOptionPane.showMessageDialog(null, "Você Ganhou! Seu oponente selecionou Pedra", "Vitoria", JOptionPane.PLAIN_MESSAGE);
              }else if(jRbtnPedra.isSelected()){
                  JOptionPane.showMessageDialog(null, "Empate! Seu oponente selecionou Pedra", "Empate", JOptionPane.PLAIN_MESSAGE);
              }else{
                  JOptionPane.showMessageDialog(null, "Você Perdeu! Seu oponente selecionou Pedra", "Derrota", JOptionPane.PLAIN_MESSAGE);
              }
           }
                if(Computador == 1){
                    if(jRbtnPapel.isSelected()){
                  JOptionPane.showMessageDialog(null, "Empate! Seu oponente selecionou Papel", "Empate", JOptionPane.PLAIN_MESSAGE);
              }else if(jRbtnPedra.isSelected()){
                  JOptionPane.showMessageDialog(null, "Você Perdeu! Seu oponente selecionou Papel", "Derrota", JOptionPane.PLAIN_MESSAGE);
              }else{
                  JOptionPane.showMessageDialog(null, "Você Ganhou! Seu oponente selecionou Papel", "Empate", JOptionPane.PLAIN_MESSAGE);
              }
                }
                if(Computador == 2){
                      if(jRbtnPapel.isSelected()){
                  JOptionPane.showMessageDialog(null, "Você Perdeu! Seu oponente selecionou Tesoura", "Derrota ", JOptionPane.PLAIN_MESSAGE);
              }else if(jRbtnPedra.isSelected()){
                  JOptionPane.showMessageDialog(null, "Você Ganhou! Seu oponente selecionou Tesoura", "Vitoria", JOptionPane.PLAIN_MESSAGE);
              }else{
                  JOptionPane.showMessageDialog(null, "Empate! Seu oponente selecionou Tesoura", "Empate", JOptionPane.PLAIN_MESSAGE);
              }
                }
            
            
            
            jBtnJogar.setText("Reiniciar");
        }else if(jBtnJogar.getText()=="Reiniciar"){
            jBtnJogar.setText("Jogar");
            jRbtnPedra.setSelected(true);
            jRbtnPapel.setSelected(false);
            jRbtnTesoura.setSelected(false);
        }
    }//GEN-LAST:event_jBtnJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnJogar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRbtnPapel;
    private javax.swing.JRadioButton jRbtnPedra;
    private javax.swing.JRadioButton jRbtnTesoura;
    // End of variables declaration//GEN-END:variables
}
