
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author felip
 */
public class Exercício1peso extends javax.swing.JFrame {

    /**
     * Creates new form Exercício1peso
     */
    public Exercício1peso() {
        initComponents();
        radiobtnMercurio.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radiobtnVenus = new javax.swing.JRadioButton();
        radiobtnMarte = new javax.swing.JRadioButton();
        radiobtnJupiter = new javax.swing.JRadioButton();
        radiobtnSaturno = new javax.swing.JRadioButton();
        radiobtnUrano = new javax.swing.JRadioButton();
        radiobtnMercurio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JToggleButton();
        jtxtPeso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(radiobtnVenus);
        radiobtnVenus.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        radiobtnVenus.setText("Vênus");

        buttonGroup1.add(radiobtnMarte);
        radiobtnMarte.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        radiobtnMarte.setText("Marte");

        buttonGroup1.add(radiobtnJupiter);
        radiobtnJupiter.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        radiobtnJupiter.setText("Júpiter");

        buttonGroup1.add(radiobtnSaturno);
        radiobtnSaturno.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        radiobtnSaturno.setText("Saturno");

        buttonGroup1.add(radiobtnUrano);
        radiobtnUrano.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        radiobtnUrano.setText("Urano");

        buttonGroup1.add(radiobtnMercurio);
        radiobtnMercurio.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        radiobtnMercurio.setText("Mercúrio");
        radiobtnMercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnMercurioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Selecione o Planeta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobtnMercurio)
                            .addComponent(radiobtnVenus))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobtnMarte)
                            .addComponent(radiobtnJupiter))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobtnSaturno)
                            .addComponent(radiobtnUrano)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radiobtnMarte)
                        .addGap(28, 28, 28)
                        .addComponent(radiobtnJupiter))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radiobtnSaturno)
                        .addGap(28, 28, 28)
                        .addComponent(radiobtnUrano))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radiobtnMercurio)
                        .addGap(28, 28, 28)
                        .addComponent(radiobtnVenus)))
                .addGap(22, 22, 22))
        );

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalcular.setText("Calcular peso");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jtxtPeso.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPesoActionPerformed(evt);
            }
        });

        jLabel2.setText("Peso na Terra(Kg)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jtxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String pesoCalcularStr = jtxtPeso.getText();
        Double pesoCalculado = 0.0;
        DecimalFormat numberFormat = new DecimalFormat("#.00");
        try{
            double pesoCalcular = Double.parseDouble(pesoCalcularStr);
            
            if (radiobtnMercurio.isSelected() == true) {
                pesoCalculado = (pesoCalcular ) * 0.37;
                JOptionPane.showMessageDialog(null, "Seu peso em Mercurio é: "+numberFormat.format(pesoCalculado)+"Kg", "Sucesso", JOptionPane.PLAIN_MESSAGE);
            } else if (radiobtnMarte.isSelected() == true) {
                pesoCalculado = (pesoCalcular ) * 0.38;
                JOptionPane.showMessageDialog(null, "Seu peso em Marte é: "+numberFormat.format(pesoCalculado)+"Kg", "Sucesso", JOptionPane.PLAIN_MESSAGE);
            } else if (radiobtnSaturno.isSelected() == true) {
                pesoCalculado = (pesoCalcular ) * 1.15;
                JOptionPane.showMessageDialog(null, "Seu peso em Saturno é: "+numberFormat.format(pesoCalculado)+"Kg", "Sucesso", JOptionPane.PLAIN_MESSAGE);
            } else if (radiobtnVenus.isSelected() == true) {
                pesoCalculado = (pesoCalcular ) * 0.88;
                JOptionPane.showMessageDialog(null, "Seu peso em Venus é: "+numberFormat.format(pesoCalculado)+"Kg", "Sucesso", JOptionPane.PLAIN_MESSAGE);
            } else if (radiobtnUrano.isSelected() == true) {
                pesoCalculado = (pesoCalcular ) * 1.17;
                JOptionPane.showMessageDialog(null, "Seu peso em Urano é: "+numberFormat.format(pesoCalculado)+"Kg", "Sucesso", JOptionPane.PLAIN_MESSAGE);
            } else if (radiobtnJupiter.isSelected() == true) {
                pesoCalculado = (pesoCalcular ) * 2.64;
                JOptionPane.showMessageDialog(null, "Seu peso em Jupiter é: "+numberFormat.format(pesoCalculado)+"Kg", "Sucesso", JOptionPane.PLAIN_MESSAGE);
            }
            
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Insira apenas números para calcular o peso", "Atenção", JOptionPane.PLAIN_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jtxtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPesoActionPerformed

    private void radiobtnMercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnMercurioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnMercurioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercício1peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercício1peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercício1peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercício1peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercício1peso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtxtPeso;
    private javax.swing.JRadioButton radiobtnJupiter;
    private javax.swing.JRadioButton radiobtnMarte;
    private javax.swing.JRadioButton radiobtnMercurio;
    private javax.swing.JRadioButton radiobtnSaturno;
    private javax.swing.JRadioButton radiobtnUrano;
    private javax.swing.JRadioButton radiobtnVenus;
    // End of variables declaration//GEN-END:variables
}
